version: '3.7'
services: 
  poshmarvel:
    build: 
      context: .
    container_name: poshmarvel
    volumes: 
      - static_data:/vol/web
    ports:
      - "8000:8000"
    environment: 
      - SECRET_KEY=samplesecretkey123
      - ALLOWED_HOSTS=127.0.0.1,localhost
  
  proxy:
    build:
      context: ./proxy
    container_name: proxy
    volumes: 
      - static_data:/vol/static
    ports:
      - "8080:8080"
    depends_on: 
      - poshmarvel

volumes: 
  static_data: